### ISSUE TITLE
Where can I find these articles

### ISSUE THREAD

**Issue by j16180339887** [yan12125/blog#1]
Hi

Is there a link to your blog, or maybe a rss feed url?

Thanks.

**Comment by yan12125** [comment]
Currently you can find those articles at https://chyen.csie.org/blog/. I plan to move them to https://blog.chyen.cc/ when I have time.

I'll check how to create RSS feeds with pelican after moving this to the new domain. Thanks for being interested in this!

**Comment by yan12125** [comment]
The blog has been moved to https://blog.chyen.cc/, and an Atom feed is available https://blog.chyen.cc/feeds/all.atom.xml
